name: Catlog Service

on:
  push:
    paths:
      - catlog-service/**
    branches:
      - 'main'
  pull_request:
    paths:
      - catlog-service/**
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/bookstore-catlog-service

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Change to Working Directory
        run: cd catlog-service

      - name: Make Maven wrapper executable
        run: chmod +x catlog-service/mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify
        working-directory: catlog-service
